name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  NODE_VERSION: 22.19.0

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup node js
        uses: actions/setup-node@v4
        with:
          node-version: { { env.NODE_VERSION } }

      - name: Instal deps
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Test code
        run: npm run test

      - name: Build repo
        run: npm run build
